version: '3'
services:
  spark-master:
    image: bitnami/spark:3.5
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      # Add any other Spark configurations here
    ports:
      - '8078:8080'
    volumes:
      - spark_volume:/opt/bitnami/spark
      - shared_workspace:/opt/workspace

  spark-worker:
    #image: bitnami/spark:3.5
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - ORGANIZATION=${ORGANIZATION}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    command: /opt/bitnami/spark/bin/spark-submit /app/main.py
    # command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "8082:8000"
      - "4041:4040"
    depends_on:
      - spark-master
    volumes:
      - ./app:/app/
      - shared_workspace:/opt/workspace

  # jupyterlab:
  #   image: jupyter/pyspark-notebook
  #   container_name: jupyterlab
  #   ports:
  #     - "82:8888"
  #   volumes:
  #     - shared_workspace:/opt/workspace
  #     - ./notebooks:/opt/workspace/notebooks
  #     - spark_volume:/opt/spark

volumes:
    spark_volume:
    shared_workspace:

