FROM bitnami/spark:3.5

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./app /app
COPY requirements.txt /tmp/requirements.txt

USER root
RUN apt update && apt install -y python3-pip
RUN pip3 install -r /tmp/requirements.txt


